import "./globals.css";
import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import StickyNav from "./components/StickyNav";
import "@fontsource-variable/quicksand";
import { HiMagnifyingGlass } from "react-icons/hi2";
import PurpleMsg from "./components/PurpleMsg";
import SearchBar from "./components/SearchBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <section className=" bg-ThemeDarkPink text-center text-white font-bold text-[14.45px] py-1.5">
          &#10024; Free Shipping US$50+ &#10024;
        </section>
        <NavBar />
        <StickyNav />

        <SearchBar />
        <PurpleMsg />

        {children}
      </body>
    </html>
  );
}
