export const NavItems = [
  "New",
  "Plush & Toys",
  "Stationery",
  "Accessories",
  "Bags",
  "Clothing",
  "Home ",
  "Candy & Snacks",
  "Shop By",
];

export const NavItemsItems = [
  ["Summer Arrivals", "All New Products", "Exclusives"],
  [
    "Plushies",
    "Gachapon Capsules",
    "Blind Boxes",
    "Collectibles",
    "Dolls & Figures",
    "Squishies",
    "Games & Toys",
    "DIY & Craft",
    "Gift Bags & Boxes",
  ],
  [
    "Pencil Cases",
    "Pens & Pencils",
    "Tapes & Stickers",
    "Highlighters & Markers",
    "Erasers",
    "Letters & Cards",
    "Notebooks & Pads",
    "Sticky Notes",
    "Office",
    "More Stationery",
  ],
  [
    "Wallets & Purses",
    "Jewelry & Watches",
    "Phone Cases & Tech",
    "Lanyards & Card Holders",
    "Keychains & Charms",
    "Badges & Pins",
    "Hair Goods",
    "Travel",
    "Umbrellas",
    "Face Masks",
    "Headwear",
    "Beauty",
  ],
  [
    "Backpacks",
    "Handbags",
    "Shoulder Bags",
    "Tote Bags",
    "Makeup Bags",
    "Lunch Bags",
    "Wallets & Purses",
    "Pouches",
  ],

  [
    "T-Shirts & Tops",
    "Bottoms",
    "Skirts",
    "Socks",
    "Slippers",
    "Loungewear",
    "Headwear",
  ],
  [
    "Bento & Lunch Boxes",
    "Drinkware",
    "Dining",
    "Kitchen",
    "Bath",
    "Beauty",
    "Office",
    "Home Goods",
  ],
  [
    "Candy",
    "Kawaii Candy",
    "DIY Candy",
    "Snacks",
    "Anime Snacks",
    "Cookies & Biscuits",
    "Chocolate",
    "Food & Drinks",
  ],
  ["Characters", "Brands", "Manufacturers", "Exclusives"],
];
